[mgr]
cwd = { fg = "#9ece6a" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#bb9af7" }
find_position = { fg = "#013198" }

marker_copied = { fg = "#7aa2f7", bg = "#7aa2f7" }
marker_cut = { fg = "#f7768e", bg = "#f7768e" }
marker_selected = { fg = "#bb9af7", bg = "#bb9af7" }

tab_inactive = { fg = "#ffffff" }
tab_active = { fg = "#1a1b26", bg = "#ffffff"}

count_copied = { fg = "#1a1b26", bg = "#7aa2f7" }
count_cut = { fg = "#1a1b26", bg = "#f7768e" }
count_selected = { fg = "#1a1b26", bg = "#bb9af7" }

border_style = { fg = "#4e7b1e" }

[mode]
normal_main = { fg = "#1a1b26", bg = "#4e7b1e", bold = true }
normal_alt = { fg = "#4e7b1e", bg = "#33354a" }

select_alt = { fg = "#013198", bg = "#33354a" }
select_main = { fg = "#1a1b26", bg = "#013198", bold = true }

unset_main = { fg = "#1a1b26", bg = "#f7768e", bold = true }
unset_alt = { fg = "#f7768e", bg = "#33354a" }

[status]
perm_exec = { fg = "#7aa2f7" }
perm_read = { fg = "#bb9af7" }
perm_sep = { fg = "#9ece6a" }
perm_type = { fg = "#4e7b1e" }
perm_write = { fg = "#f7768e" }

progress_error = { fg = "#f7768e", bg = "#1a1b26" }
progress_label = { fg = "#ffffff", bg = "#1a1b26" }
progress_normal = { fg = "#ffffff", bg = "#1a1b26" }

[pick]
active = { fg = "#013198" }
border = { fg = "#4e7b1e" }
inactive = { fg = "#ffffff" }

[task]
title = { fg = "#4e7b1e" }
border = { fg = "#4e7b1e" }
hovered = { fg = "#ffffff", bg = "#33354a" }

[input]
border = { fg = "#4e7b1e" }
selected = { bg = "#33354a" }

[help]
desc = { fg = "#ffffff" }
on = { fg = "#9ece6a" }
run = { fg = "#013198" }
hovered = { reversed = true, bold = true }
footer = { fg = "#33354a", bg = "#ffffff" }

[which]
mask = { bg = "#33354a" }
desc = { fg = "#ffffff" }
cand = { fg = "#9ece6a" }
rest = { fg = "#98011d" }

separator_style = { fg = "#5e70be" }

[notify]
title_info = { fg = "#9ece6a" }
title_warn = { fg = "#bb9af7" }
title_error = { fg = "#f7768e" }

[filetype]
rules = [
  { mime = "image/*", fg = "#9ece6a" },
  { mime = "{audio, video}/*", fg = "#bb9af7" },

  { mime = "application/{pdf,doc,rtf}", fg = "#7aa2f7" },

  { mime = "application/" },

  { mime = "inode/directory", fg = "#4e7b1e" },
  { mime = "*", fg = "#ffffff" },
]

