[colors]
ansi = [
    "#090618",
    "#c34043",
    "#76946a",
    "#c0a36e",
    "#7e9cd8",
    "#957fb8",
    "#6a9589",
    "#dcd7ba",
]
background = "#1f1f28"
brights = [
    "#727169",
    "#e82424",
    "#98bb6c",
    "#e6c384",
    "#7fb4ca",
    "#938aa9",
    "#7aa89f",
    "#c8c093",
]
cursor_bg = "#dcd7ba"
cursor_border = "#dcd7ba"
cursor_fg = "#1f1f28"
foreground = "#dcd7ba"

[colors.indexed]

[metadata]
name = "Noctalia"
