[colors]
ansi = [
    "#191919",
    "#dddddd",
    "#cccccc",
    "#aaaaaa",
    "#a7a7a7",
    "#dddddd",
    "#cccccc",
    "#828282",
]
background = "#111111"
brights = [
    "#3c3c3c",
    "#dddddd",
    "#cccccc",
    "#aaaaaa",
    "#a7a7a7",
    "#dddddd",
    "#cccccc",
    "#ffffff",
]
cursor_bg = "#aaaaaa"
cursor_border = "#aaaaaa"
cursor_fg = "#111111"
foreground = "#828282"
selection_bg = "#828282"
selection_fg = "#111111"

[metadata]
name = "Noctalia"
