[colors]
ansi = [
    "#e8e8e8",
    "#222222",
    "#333333",
    "#555555",
    "#505058",
    "#222222",
    "#333333",
    "#696969",
]
background = "#d4d4d4"
brights = [
    "#c3c3c3",
    "#222222",
    "#333333",
    "#555555",
    "#505058",
    "#222222",
    "#333333",
    "#000000",
]
cursor_bg = "#555555"
cursor_border = "#555555"
cursor_fg = "#d4d4d4"
foreground = "#696969"
selection_bg = "#696969"
selection_fg = "#d4d4d4"

[metadata]
name = "Noctalia"
