[mgr]
cwd = { fg = "{{colors.tertiary.default.hex}}" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "{{colors.secondary.default.hex}}" }
find_position = { fg = "{{colors.primary_container.default.hex}}" }

marker_copied = { fg = "{{colors.primary.default.hex}}", bg = "{{colors.primary.default.hex}}" }
marker_cut = { fg = "{{colors.error.default.hex}}", bg = "{{colors.error.default.hex}}" }
marker_selected = { fg = "{{colors.secondary.default.hex}}", bg = "{{colors.secondary.default.hex}}" }

tab_inactive = { fg = "{{colors.on_surface.default.hex}}" }
tab_active = { fg = "{{colors.surface.default.hex}}", bg = "{{colors.on_surface.default.hex}}"}

count_copied = { fg = "{{colors.surface.default.hex}}", bg = "{{colors.primary.default.hex}}" }
count_cut = { fg = "{{colors.surface.default.hex}}", bg = "{{colors.error.default.hex}}" }
count_selected = { fg = "{{colors.surface.default.hex}}", bg = "{{colors.secondary.default.hex}}" }

border_style = { fg = "{{colors.tertiary_container.default.hex}}" }

[mode]
normal_main = { fg = "{{colors.surface.default.hex}}", bg = "{{colors.tertiary_container.default.hex}}", bold = true }
normal_alt = { fg = "{{colors.tertiary_container.default.hex}}", bg = "{{colors.surface_container_highest.default.hex}}" }

select_alt = { fg = "{{colors.primary_container.default.hex}}", bg = "{{colors.surface_container_highest.default.hex}}" }
select_main = { fg = "{{colors.surface.default.hex}}", bg = "{{colors.primary_container.default.hex}}", bold = true }

unset_main = { fg = "{{colors.surface.default.hex}}", bg = "{{colors.error.default.hex}}", bold = true }
unset_alt = { fg = "{{colors.error.default.hex}}", bg = "{{colors.surface_container_highest.default.hex}}" }

[status]
perm_exec = { fg = "{{colors.primary.default.hex}}" }
perm_read = { fg = "{{colors.secondary.default.hex}}" }
perm_sep = { fg = "{{colors.tertiary.default.hex}}" }
perm_type = { fg = "{{colors.tertiary_container.default.hex}}" }
perm_write = { fg = "{{colors.error.default.hex}}" }

progress_error = { fg = "{{colors.error.default.hex}}", bg = "{{colors.surface.default.hex}}" }
progress_label = { fg = "{{colors.on_surface.default.hex}}", bg = "{{colors.surface.default.hex}}" }
progress_normal = { fg = "{{colors.on_surface.default.hex}}", bg = "{{colors.surface.default.hex}}" }

[pick]
active = { fg = "{{colors.primary_container.default.hex}}" }
border = { fg = "{{colors.tertiary_container.default.hex}}" }
inactive = { fg = "{{colors.on_surface.default.hex}}" }

[task]
title = { fg = "{{colors.tertiary_container.default.hex}}" }
border = { fg = "{{colors.tertiary_container.default.hex}}" }
hovered = { fg = "{{colors.on_surface.default.hex}}", bg = "{{colors.surface_container_highest.default.hex}}" }

[input]
border = { fg = "{{colors.tertiary_container.default.hex}}" }
selected = { bg = "{{colors.surface_container_highest.default.hex}}" }

[help]
desc = { fg = "{{colors.on_surface.default.hex}}" }
on = { fg = "{{colors.tertiary.default.hex}}" }
run = { fg = "{{colors.primary_container.default.hex}}" }
hovered = { reversed = true, bold = true }
footer = { fg = "{{colors.surface_container_highest.default.hex}}", bg = "{{colors.on_surface.default.hex}}" }

[which]
mask = { bg = "{{colors.surface_container_highest.default.hex}}" }
desc = { fg = "{{colors.on_surface.default.hex}}" }
cand = { fg = "{{colors.tertiary.default.hex}}" }
rest = { fg = "{{colors.error_container.default.hex}}" }

separator_style = { fg = "{{colors.outline.default.hex}}" }

[notify]
title_info = { fg = "{{colors.tertiary.default.hex}}" }
title_warn = { fg = "{{colors.secondary.default.hex}}" }
title_error = { fg = "{{colors.error.default.hex}}" }

[filetype]
rules = [
  { mime = "image/*", fg = "{{colors.tertiary.default.hex}}" },
  { mime = "{audio, video}/*", fg = "{{colors.secondary.default.hex}}" },

  { mime = "application/{pdf,doc,rtf}", fg = "{{colors.primary.default.hex}}" },

  { mime = "application/" },

  { mime = "inode/directory", fg = "{{colors.tertiary_container.default.hex}}" },
  { mime = "*", fg = "{{colors.on_surface.default.hex}}" },
]

